// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se;

import com.se.Sdadsd;

privileged aspect Sdadsd_Roo_JavaBean {
    
    public String Sdadsd.getName() {
        return this.name;
    }
    
    public void Sdadsd.setName(String name) {
        this.name = name;
    }
    
}
